### ISSUE TITLE
Debian 11 -> debian 12

### ISSUE THREAD

**Issue by ErikEngerd** [NVIDIA/k8s-device-plugin#471]
### 1. Issue or feature description

I previously had a working setup with debian 11 and now decided to add a kubernetes node to debian 12 using a fresh install of debian. 

Observations:
* the nvidia driver is successfully loaded on the kubernetes node
* the nvidia driver can also be seen as loaded in an example pod that is running `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2`. To verify this, I do 
```
apt update
apt-get install kmod -y 
lsmod | grep nvidia
```
* In that container, nvidia-smi also gives correct output, but the default command of the container results in
 ```
 Failed to allocate device vector A (error code no CUDA-capable device is detected)!
[Vector addition of 50000 elements]
 ```
* I have configure the nvidia runtime as the default runtime. If I use `chmod 0 /usr/bin/nvidia-container-runtime` on the kubernetes node, then my gpu-pod will not start because of 'Failed to create pod sandbox....` errors in the kubectl describe output of the pod. 
* Running the container on the kubernetes node using ctr gives the same errors:
```
ctr i pull nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
# shows correct output
ctr run --rm --gpus 0 -t nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2 n nvidia-smi
# gives the same error as the pod 
ctr run --rm --gpus 0 -t nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2 n 

```

In the setup I have followed the standard instructions for installing the kubernetes node (which is running fine) and the instructions for installing the device plugin at https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#debian

In addition, I configured nvidia as the default runtime and set `SystemdC group = true` in  `[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]`. 

### 2. Steps to reproduce the issue

See above

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
 - [ ] The output of `nvidia-smi -a` on your host
```
==============NVSMI LOG==============

Timestamp                                 : Sun Dec 24 15:29:50 2023
Driver Version                            : 545.23.08
CUDA Version                              : Not Found

Attached GPUs                             : 1
GPU 00000000:0A:00.0
    Product Name                          : NVIDIA GeForce RTX 3090
    Product Brand                         : GeForce
    Product Architecture                  : Ampere
    Display Mode                          : Disabled
    Display Active                        : Disabled
    Persistence Mode                      : Enabled
    Addressing Mode                       : None
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : N/A
    GPU UUID                              : GPU-e6599a7e-0e05-8026-e67f-c09a145a5344
    Minor Number                          : 0
    VBIOS Version                         : 94.02.59.00.DD
    MultiGPU Board                        : No
    Board ID                              : 0xa00
    Board Part Number                     : N/A
    GPU Part Number                       : 2204-300-A1
    FRU Part Number                       : N/A
    Module ID                             : 1
    Inforom Version
        Image Version                     : G001.0000.03.03
        OEM Object                        : 2.0
        ECC Object                        : N/A
        Power Management Object           : N/A
    Inforom BBX Object Flush
        Latest Timestamp                  : N/A
        Latest Duration                   : N/A
    GPU Operation Mode
        Current                           : N/A
        Pending                           : N/A
    GSP Firmware Version                  : N/A
    GPU C2C Mode                          : N/A
    GPU Virtualization Mode
        Virtualization Mode               : Pass-Through
        Host VGPU Mode                    : N/A
    GPU Reset Status
        Reset Required                    : No
        Drain and Reset Recommended       : N/A
    IBMNPU
        Relaxed Ordering Mode             : N/A
    PCI
        Bus                               : 0x0A
        Device                            : 0x00
        Domain                            : 0x0000
        Device Id                         : 0x220410DE
        Bus Id                            : 00000000:0A:00.0
        Sub System Id                     : 0x145410DE
        GPU Link Info
            PCIe Generation
                Max                       : 3
                Current                   : 1
                Device Current            : 1
                Device Max                : 4
                Host Max                  : N/A
            Link Width
                Max                       : 16x
                Current                   : 16x
        Bridge Chip
            Type                          : N/A
            Firmware                      : N/A
        Replays Since Reset               : 0
        Replay Number Rollovers           : 0
        Tx Throughput                     : 0 KB/s
        Rx Throughput                     : 0 KB/s
        Atomic Caps Inbound               : N/A
        Atomic Caps Outbound              : N/A
    Fan Speed                             : 0 %
    Performance State                     : P8
    Clocks Event Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active
    FB Memory Usage
        Total                             : 24576 MiB
        Reserved                          : 316 MiB
        Used                              : 3 MiB
        Free                              : 24256 MiB
    BAR1 Memory Usage
        Total                             : 256 MiB
        Used                              : 2 MiB
        Free                              : 254 MiB
    Conf Compute Protected Memory Usage
        Total                             : 0 MiB
        Used                              : 0 MiB
        Free                              : 0 MiB
    Compute Mode                          : Default
    Utilization
        Gpu                               : 0 %
        Memory                            : 0 %
        Encoder                           : 0 %
        Decoder                           : 0 %
        JPEG                              : 0 %
        OFA                               : 0 %
    Encoder Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    FBC Stats
        Active Sessions                   : 0
        Average FPS                       : 0
        Average Latency                   : 0
    ECC Mode
        Current                           : N/A
        Pending                           : N/A
    ECC Errors
        Volatile
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
        Aggregate
            SRAM Correctable              : N/A
            SRAM Uncorrectable            : N/A
            DRAM Correctable              : N/A
            DRAM Uncorrectable            : N/A
    Retired Pages
        Single Bit ECC                    : N/A
        Double Bit ECC                    : N/A
        Pending Page Blacklist            : N/A
    Remapped Rows                         : N/A
    Temperature
        GPU Current Temp                  : 30 C
        GPU T.Limit Temp                  : N/A
        GPU Shutdown Temp                 : 98 C
        GPU Slowdown Temp                 : 95 C
        GPU Max Operating Temp            : 93 C
        GPU Target Temperature            : 83 C
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
    GPU Power Readings
        Power Draw                        : 9.54 W
        Current Power Limit               : 370.00 W
        Requested Power Limit             : 370.00 W
        Default Power Limit               : 370.00 W
        Min Power Limit                   : 100.00 W
        Max Power Limit                   : 370.00 W
    GPU Memory Power Readings 
        Power Draw                        : N/A
    Module Power Readings
        Power Draw                        : N/A
        Current Power Limit               : N/A
        Requested Power Limit             : N/A
        Default Power Limit               : N/A
        Min Power Limit                   : N/A
        Max Power Limit                   : N/A
    Clocks
        Graphics                          : 0 MHz
        SM                                : 0 MHz
        Memory                            : 405 MHz
        Video                             : 555 MHz
    Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Default Applications Clocks
        Graphics                          : N/A
        Memory                            : N/A
    Deferred Clocks
        Memory                            : N/A
    Max Clocks
        Graphics                          : 2115 MHz
        SM                                : 2115 MHz
        Memory                            : 9751 MHz
        Video                             : 1950 MHz
    Max Customer Boost Clocks
        Graphics                          : N/A
    Clock Policy
        Auto Boost                        : N/A
        Auto Boost Default                : N/A
    Voltage
        Graphics                          : 0.000 mV
    Fabric
        State                             : N/A
        Status                            : N/A
    Processes                             : None
```
 - containerd config file
```
disabled_plugins = []
imports = []
oom_score = 0
plugin_dir = ""
required_plugins = []
root = "/var/lib/containerd"
state = "/run/containerd"
temp = ""
version = 2

[cgroup]
  path = ""

[debug]
  address = ""
  format = ""
  gid = 0
  level = ""
  uid = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216
  tcp_address = ""
  tcp_tls_ca = ""
  tcp_tls_cert = ""
  tcp_tls_key = ""
  uid = 0

[metrics]
  address = ""
  grpc_histogram = false

[plugins]

  [plugins."io.containerd.gc.v1.scheduler"]
    deletion_threshold = 0
    mutation_threshold = 100
    pause_threshold = 0.02
    schedule_delay = "0s"
    startup_delay = "100ms"

  [plugins."io.containerd.grpc.v1.cri"]
    device_ownership_from_security_context = false
    disable_apparmor = false
    disable_cgroup = false
    disable_hugetlb_controller = true
    disable_proc_mount = false
    disable_tcp_service = true
    enable_selinux = false
    enable_tls_streaming = false
    enable_unprivileged_icmp = false
    enable_unprivileged_ports = false
    ignore_image_defined_volumes = false
    max_concurrent_downloads = 3
    max_container_log_line_size = 16384
    netns_mounts_under_state_dir = false
    restrict_oom_score_adj = false
    sandbox_image = "registry.k8s.io/pause:3.6"
    selinux_category_range = 1024
    stats_collect_period = 10
    stream_idle_timeout = "4h0m0s"
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    systemd_cgroup = false
    tolerate_missing_hugetlb_controller = true
    unset_seccomp_profile = ""

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      conf_template = ""
      ip_pref = ""
      max_conf_num = 1

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      ignore_rdt_not_enabled_errors = false
      no_pivot = false
      snapshotter = "overlayfs"

      [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
        base_runtime_spec = ""
        cni_conf_dir = ""
        cni_max_conf_num = 0
        container_annotations = []
        pod_annotations = []
        privileged_without_host_devices = false
        runtime_engine = ""
        runtime_path = ""
        runtime_root = ""
        runtime_type = ""

        [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime.options]

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          base_runtime_spec = ""
          cni_conf_dir = ""
          cni_max_conf_num = 0
          container_annotations = []
          pod_annotations = []
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_path = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"
            CriuImagePath = ""
            CriuPath = ""
            CriuWorkPath = ""
            IoGid = 0
            IoUid = 0
            NoNewKeyring = false
            NoPivotRoot = false
            Root = ""
            ShimCgroup = ""
            SystemdCgroup = true

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          base_runtime_spec = ""
          cni_conf_dir = ""
          cni_max_conf_num = 0
          container_annotations = []
          pod_annotations = []
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_path = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            BinaryName = ""
            CriuImagePath = ""
            CriuPath = ""
            CriuWorkPath = ""
            IoGid = 0
            IoUid = 0
            NoNewKeyring = false
            NoPivotRoot = false
            Root = ""
            ShimCgroup = ""
            SystemdCgroup = true

      [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
        base_runtime_spec = ""
        cni_conf_dir = ""
        cni_max_conf_num = 0
        container_annotations = []
        pod_annotations = []
        privileged_without_host_devices = false
        runtime_engine = ""
        runtime_path = ""
        runtime_root = ""
        runtime_type = ""

        [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime.options]

    [plugins."io.containerd.grpc.v1.cri".image_decryption]
      key_model = "node"

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = ""

      [plugins."io.containerd.grpc.v1.cri".registry.auths]

      [plugins."io.containerd.grpc.v1.cri".registry.configs]

      [plugins."io.containerd.grpc.v1.cri".registry.headers]

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]

    [plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""

  [plugins."io.containerd.internal.v1.opt"]
    path = "/opt/containerd"

  [plugins."io.containerd.internal.v1.restart"]
    interval = "10s"

  [plugins."io.containerd.metadata.v1.bolt"]
    content_sharing_policy = "shared"

  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = false

  [plugins."io.containerd.runtime.v1.linux"]
    no_shim = false
    runtime = "runc"
    runtime_root = ""
    shim = "containerd-shim"
    shim_debug = false

  [plugins."io.containerd.runtime.v2.task"]
    platforms = ["linux/amd64"]
    sched_core = false

  [plugins."io.containerd.service.v1.diff-service"]
    default = ["walking"]

  [plugins."io.containerd.service.v1.tasks-service"]
    rdt_config_file = ""

  [plugins."io.containerd.snapshotter.v1.aufs"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.btrfs"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.devmapper"]
    async_remove = false
    base_image_size = ""
    discard_blocks = false
    fs_options = ""
    fs_type = ""
    pool_name = ""
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.native"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.overlayfs"]
    root_path = ""
    upperdir_label = false

  [plugins."io.containerd.snapshotter.v1.zfs"]
    root_path = ""

[proxy_plugins]

[stream_processors]

  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
    args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
    env = ["OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf"]
    path = "ctd-decoder"
    returns = "application/vnd.oci.image.layer.v1.tar"

  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
    args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
    env = ["OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf"]
    path = "ctd-decoder"
    returns = "application/vnd.oci.image.layer.v1.tar+gzip"

[timeouts]
  "io.containerd.timeout.bolt.open" = "0s"
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

[ttrpc]
  address = ""
  gid = 0
  uid = 0

```
 - [ ] The k8s-device-plugin container logs
```
Running with config:
{
  "version": "v1",
  "flags": {
    "migStrategy": "none",
    "failOnInitError": false,
    "nvidiaDriverRoot": "/",
    "gdsEnabled": false,
    "mofedEnabled": false,
    "plugin": {
      "passDeviceSpecs": false,
      "deviceListStrategy": [
        "envvar"
      ],
      "deviceIDStrategy": "uuid",
      "cdiAnnotationPrefix": "cdi.k8s.io/",
      "nvidiaCTKPath": "/usr/bin/nvidia-ctk",
      "containerDriverRoot": "/driver-root"
    }
  },
  "resources": {
    "gpus": [
      {
        "pattern": "*",
        "name": "nvidia.com/gpu"
      }
    ]
  },
  "sharing": {
    "timeSlicing": {
      "resources": [
        {
          "name": "nvidia.com/gpu",
          "devices": "all",
          "replicas": 5
        }
      ]
    }
  }
}
I1224 14:02:47.169759       1 main.go:256] Retreiving plugins.
I1224 14:02:47.250476       1 factory.go:107] Detected NVML platform: found NVML library
I1224 14:02:47.250529       1 factory.go:107] Detected non-Tegra platform: /sys/devices/soc0/family file not found
I1224 14:02:47.268402       1 server.go:165] Starting GRPC server for 'nvidia.com/gpu'
I1224 14:02:47.322634       1 server.go:117] Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
I1224 14:02:47.323938       1 server.go:125] Registered device plugin for 'nvidia.com/gpu' with Kubelet
```
 - [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
```
Dec 24 15:36:14 weasel kubelet[9577]: I1224 15:36:14.405191    9577 kubelet_volumes.go:161] "Cleaned up orphaned pod volumes dir" podUID=f339d815-551f-47a7-9f86-bbbe57153c9d path="/var/lib/kubelet/pods/f339d815-551f-47a7-9f86-bbbe57153c9d/volumes"
Dec 24 15:36:21 weasel kubelet[9577]: I1224 15:36:21.815572    9577 topology_manager.go:212] "Topology Admit Handler"
Dec 24 15:36:21 weasel kubelet[9577]: E1224 15:36:21.840903    9577 cpu_manager.go:395] "RemoveStaleState: removing container" podUID="f339d815-551f-47a7-9f86-bbbe57153c9d" containerName="cuda-container"
Dec 24 15:36:21 weasel kubelet[9577]: I1224 15:36:21.840983    9577 memory_manager.go:346] "RemoveStaleState removing state" podUID="f339d815-551f-47a7-9f86-bbbe57153c9d" containerName="cuda-container"
Dec 24 15:36:21 weasel kubelet[9577]: I1224 15:36:21.918211    9577 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-6sqdq\" (UniqueName: \"kubernetes.io/projected/6c33fc67-1719-4b09-9bcb-78fa48e33244-kube-api-access-6sqdq\") pod \"gpu-pod\" (UID: \"6c33fc67-1719-4b09-9bcb-78fa48e33244\") " pod="default/gpu-pod"
Dec 24 15:36:24 weasel kubelet[9577]: I1224 15:36:24.936027    9577 scope.go:115] "RemoveContainer" containerID="7653b93019478d85200fa9d8ee3211919e940eb5f7a2f606e18d972de018f362"
Dec 24 15:36:25 weasel kubelet[9577]: I1224 15:36:25.137786    9577 reconciler_common.go:172] "operationExecutor.UnmountVolume started for volume \"kube-api-access-6sqdq\" (UniqueName: \"kubernetes.io/projected/6c33fc67-1719-4b09-9bcb-78fa48e33244-kube-api-access-6sqdq\") pod \"6c33fc67-1719-4b09-9bcb-78fa48e33244\" (UID: \"6c33fc67-1719-4b09-9bcb-78fa48e33244\") "
Dec 24 15:36:25 weasel kubelet[9577]: I1224 15:36:25.138865    9577 operation_generator.go:878] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/6c33fc67-1719-4b09-9bcb-78fa48e33244-kube-api-access-6sqdq" (OuterVolumeSpecName: "kube-api-access-6sqdq") pod "6c33fc67-1719-4b09-9bcb-78fa48e33244" (UID: "6c33fc67-1719-4b09-9bcb-78fa48e33244"). InnerVolumeSpecName "kube-api-access-6sqdq". PluginName "kubernetes.io/projected", VolumeGidValue ""
Dec 24 15:36:25 weasel kubelet[9577]: I1224 15:36:25.238806    9577 reconciler_common.go:300] "Volume detached for volume \"kube-api-access-6sqdq\" (UniqueName: \"kubernetes.io/projected/6c33fc67-1719-4b09-9bcb-78fa48e33244-kube-api-access-6sqdq\") on node \"weasel\" DevicePath \"\""
Dec 24 15:36:25 weasel kubelet[9577]: I1224 15:36:25.858284    9577 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="043d5bbbb4fa12d177737e36c3e535fca091db01da0678b38a263d0f63b16310"

```

Additional information that might help better understand your environment and reproduce the bug:
 - containerd: 1.6.20~ds1-1+b1
 - image used: `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2`
 - device plugin image: `nvcr.io/nvidia/k8s-device-plugin:v0.14.3`
 - kernel version: Linux weasel 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
 - dmesg show nothing special
```
[ 2469.885030] IPv6: ADDRCONF(NETDEV_CHANGE): cali9ae405349c8: link becomes ready
[ 2470.786122] IPv6: ADDRCONF(NETDEV_CHANGE): cali9ae405349c8: link becomes ready
[ 2471.828544] IPv6: ADDRCONF(NETDEV_CHANGE): cali9ae405349c8: link becomes ready
[ 3237.398084] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 3237.398106] IPv6: ADDRCONF(NETDEV_CHANGE): cali9ae405349c8: link becomes ready

```
 - NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`: 
```
||/ Name                                   Version            Architecture Description
+++-======================================-==================-============-=================================================================
un  bumblebee-nvidia                       <none>             <none>       (no description available)
ii  glx-alternative-nvidia                 1.2.2              amd64        allows the selection of NVIDIA as GLX provider
un  libegl-nvidia-legacy-390xx0            <none>             <none>       (no description available)
un  libegl-nvidia-tesla-418-0              <none>             <none>       (no description available)
un  libegl-nvidia-tesla-440-0              <none>             <none>       (no description available)
ii  libegl-nvidia0:amd64                   545.23.08-1        amd64        NVIDIA binary EGL library
ii  libegl-nvidia0:i386                    545.23.08-1        i386         NVIDIA binary EGL library
un  libegl1-glvnd-nvidia                   <none>             <none>       (no description available)
un  libegl1-nvidia                         <none>             <none>       (no description available)
un  libgl1-glvnd-nvidia-glx                <none>             <none>       (no description available)
ii  libgl1-nvidia-glvnd-glx:amd64          545.23.08-1        amd64        NVIDIA binary OpenGL/GLX library (GLVND variant)
ii  libgl1-nvidia-glvnd-glx:i386           545.23.08-1        i386         NVIDIA binary OpenGL/GLX library (GLVND variant)
un  libgl1-nvidia-glx                      <none>             <none>       (no description available)
un  libgl1-nvidia-glx-any                  <none>             <none>       (no description available)
un  libgl1-nvidia-glx-i386                 <none>             <none>       (no description available)
un  libgl1-nvidia-legacy-390xx-glx         <none>             <none>       (no description available)
un  libgl1-nvidia-tesla-418-glx            <none>             <none>       (no description available)
un  libgldispatch0-nvidia                  <none>             <none>       (no description available)
ii  libgles-nvidia1:amd64                  545.23.08-1        amd64        NVIDIA binary OpenGL|ES 1.x library
ii  libgles-nvidia1:i386                   545.23.08-1        i386         NVIDIA binary OpenGL|ES 1.x library
ii  libgles-nvidia2:amd64                  545.23.08-1        amd64        NVIDIA binary OpenGL|ES 2.x library
ii  libgles-nvidia2:i386                   545.23.08-1        i386         NVIDIA binary OpenGL|ES 2.x library
un  libgles1-glvnd-nvidia                  <none>             <none>       (no description available)
un  libgles2-glvnd-nvidia                  <none>             <none>       (no description available)
un  libglvnd0-nvidia                       <none>             <none>       (no description available)
ii  libglx-nvidia0:amd64                   545.23.08-1        amd64        NVIDIA binary GLX library
ii  libglx-nvidia0:i386                    545.23.08-1        i386         NVIDIA binary GLX library
un  libglx0-glvnd-nvidia                   <none>             <none>       (no description available)
ii  libnvidia-cfg1:amd64                   545.23.08-1        amd64        NVIDIA binary OpenGL/GLX configuration library
un  libnvidia-cfg1-any                     <none>             <none>       (no description available)
ii  libnvidia-container-tools              1.14.3-1           amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64             1.14.3-1           amd64        NVIDIA container runtime library
ii  libnvidia-eglcore:amd64                545.23.08-1        amd64        NVIDIA binary EGL core libraries
ii  libnvidia-eglcore:i386                 545.23.08-1        i386         NVIDIA binary EGL core libraries
un  libnvidia-eglcore-545.23.08            <none>             <none>       (no description available)
ii  libnvidia-glcore:amd64                 545.23.08-1        amd64        NVIDIA binary OpenGL/GLX core libraries
ii  libnvidia-glcore:i386                  545.23.08-1        i386         NVIDIA binary OpenGL/GLX core libraries
un  libnvidia-glcore-545.23.08             <none>             <none>       (no description available)
ii  libnvidia-glvkspirv:amd64              545.23.08-1        amd64        NVIDIA binary Vulkan Spir-V compiler library
ii  libnvidia-glvkspirv:i386               545.23.08-1        i386         NVIDIA binary Vulkan Spir-V compiler library
un  libnvidia-glvkspirv-545.23.08          <none>             <none>       (no description available)
ii  libnvidia-gpucomp1:amd64               545.23.08-1        amd64        NVIDIA GPUCOMP runtime library
ii  libnvidia-gpucomp1:i386                545.23.08-1        i386         NVIDIA GPUCOMP runtime library
un  libnvidia-legacy-340xx-cfg1            <none>             <none>       (no description available)
un  libnvidia-legacy-390xx-cfg1            <none>             <none>       (no description available)
un  libnvidia-ml.so.1                      <none>             <none>       (no description available)
ii  libnvidia-ml1:amd64                    545.23.08-1        amd64        NVIDIA Management Library (NVML) runtime library
ii  libnvidia-rtcore:amd64                 545.23.08-1        amd64        NVIDIA binary Vulkan ray tracing (rtcore) library
un  libnvidia-rtcore-545.23.08             <none>             <none>       (no description available)
un  libnvidia-tesla-cfg1                   <none>             <none>       (no description available)
ii  libnvidia-wayland-client:amd64         545.23.08-1        amd64        NVIDIA client for wayland library
un  libnvidia-wayland-client-545.23.08     <none>             <none>       (no description available)
un  libopengl0-glvnd-nvidia                <none>             <none>       (no description available)
ii  nvidia-alternative                     545.23.08-1        amd64        allows the selection of NVIDIA as GLX provider
un  nvidia-alternative--kmod-alias         <none>             <none>       (no description available)
un  nvidia-alternative-legacy-173xx        <none>             <none>       (no description available)
un  nvidia-alternative-legacy-71xx         <none>             <none>       (no description available)
un  nvidia-alternative-legacy-96xx         <none>             <none>       (no description available)
un  nvidia-container-runtime               <none>             <none>       (no description available)
un  nvidia-container-runtime-hook          <none>             <none>       (no description available)
ii  nvidia-container-toolkit               1.14.3-1           amd64        NVIDIA Container toolkit
ii  nvidia-container-toolkit-base          1.14.3-1           amd64        NVIDIA Container Toolkit Base
un  nvidia-current                         <none>             <none>       (no description available)
un  nvidia-current-updates                 <none>             <none>       (no description available)
ii  nvidia-driver                          545.23.08-1        amd64        NVIDIA metapackage
un  nvidia-driver-any                      <none>             <none>       (no description available)
ii  nvidia-driver-bin                      545.23.08-1        amd64        NVIDIA driver support binaries
un  nvidia-driver-bin-545.23.08            <none>             <none>       (no description available)
un  nvidia-driver-binary                   <none>             <none>       (no description available)
ii  nvidia-driver-libs:amd64               545.23.08-1        amd64        NVIDIA metapackage (OpenGL/GLX/EGL/GLES libraries)
ii  nvidia-driver-libs:i386                545.23.08-1        i386         NVIDIA metapackage (OpenGL/GLX/EGL/GLES libraries)
un  nvidia-driver-libs-any                 <none>             <none>       (no description available)
ii  nvidia-driver-libs-i386:i386           545.23.08-1        i386         NVIDIA metapackage (OpenGL/GLX/EGL/GLES 32-bit libraries)
un  nvidia-driver-libs-nonglvnd            <none>             <none>       (no description available)
ii  nvidia-egl-common                      545.23.08-1        amd64        NVIDIA binary EGL driver - common files
ii  nvidia-egl-icd:amd64                   545.23.08-1        amd64        NVIDIA EGL installable client driver (ICD)
ii  nvidia-egl-icd:i386                    545.23.08-1        i386         NVIDIA EGL installable client driver (ICD)
un  nvidia-glx-any                         <none>             <none>       (no description available)
ii  nvidia-installer-cleanup               20220217+3~deb12u1 amd64        cleanup after driver installation with the nvidia-installer
un  nvidia-kernel-545.23.08                <none>             <none>       (no description available)
ii  nvidia-kernel-common                   20220217+3~deb12u1 amd64        NVIDIA binary kernel module support files
ii  nvidia-kernel-dkms                     545.23.08-1        amd64        NVIDIA binary kernel module DKMS source
un  nvidia-kernel-open-dkms                <none>             <none>       (no description available)
un  nvidia-kernel-open-dkms-545.23.08      <none>             <none>       (no description available)
un  nvidia-kernel-source                   <none>             <none>       (no description available)
ii  nvidia-kernel-support                  545.23.08-1        amd64        NVIDIA binary kernel module support files
un  nvidia-kernel-support--v1              <none>             <none>       (no description available)
un  nvidia-kernel-support-any              <none>             <none>       (no description available)
un  nvidia-legacy-304xx-alternative        <none>             <none>       (no description available)
un  nvidia-legacy-304xx-driver             <none>             <none>       (no description available)
un  nvidia-legacy-304xx-kernel-support     <none>             <none>       (no description available)
un  nvidia-legacy-340xx-alternative        <none>             <none>       (no description available)
un  nvidia-legacy-340xx-kernel-support     <none>             <none>       (no description available)
un  nvidia-legacy-390xx-kernel-support     <none>             <none>       (no description available)
un  nvidia-legacy-390xx-vulkan-icd         <none>             <none>       (no description available)
ii  nvidia-legacy-check                    545.23.08-1        amd64        check for NVIDIA GPUs requiring a legacy driver
ii  nvidia-modprobe                        545.23.08-1        amd64        utility to load NVIDIA kernel modules and create device nodes
un  nvidia-nonglvnd-vulkan-common          <none>             <none>       (no description available)
un  nvidia-nonglvnd-vulkan-icd             <none>             <none>       (no description available)
ii  nvidia-persistenced                    545.23.08-1        amd64        daemon to maintain persistent software state in the NVIDIA driver
ii  nvidia-settings                        545.23.08-1        amd64        tool for configuring the NVIDIA graphics driver
un  nvidia-settings-gtk-545.23.08          <none>             <none>       (no description available)
ii  nvidia-smi                             545.23.08-1        amd64        NVIDIA System Management Interface
ii  nvidia-support                         20220217+3~deb12u1 amd64        NVIDIA binary graphics driver support files
un  nvidia-tesla-418-kernel-dkms           <none>             <none>       (no description available)
un  nvidia-tesla-418-kernel-support        <none>             <none>       (no description available)
un  nvidia-tesla-418-vulkan-icd            <none>             <none>       (no description available)
un  nvidia-tesla-440-kernel-support        <none>             <none>       (no description available)
un  nvidia-tesla-440-vulkan-icd            <none>             <none>       (no description available)
un  nvidia-tesla-450-kernel-support        <none>             <none>       (no description available)
un  nvidia-tesla-460-kernel-dkms           <none>             <none>       (no description available)
un  nvidia-tesla-460-kernel-support        <none>             <none>       (no description available)
un  nvidia-tesla-470-kernel-support        <none>             <none>       (no description available)
un  nvidia-tesla-alternative               <none>             <none>       (no description available)
ii  nvidia-vdpau-driver:amd64              545.23.08-1        amd64        Video Decode and Presentation API for Unix - NVIDIA driver
ii  nvidia-vulkan-common                   545.23.08-1        amd64        NVIDIA Vulkan driver - common files
ii  nvidia-vulkan-icd:amd64                545.23.08-1        amd64        NVIDIA Vulkan installable client driver (ICD)
ii  nvidia-vulkan-icd:i386                 545.23.08-1        i386         NVIDIA Vulkan installable client driver (ICD)
un  nvidia-vulkan-icd-any                  <none>             <none>       (no description available)
ii  xserver-xorg-video-nvidia              545.23.08-1        amd64        NVIDIA binary Xorg driver
un  xserver-xorg-video-nvidia-any          <none>             <none>       (no description available)
un  xserver-xorg-video-nvidia-legacy-304xx <none>             <none>       (no description available)

```
 - NVIDIA container library version from `nvidia-container-cli -V`:
```
cli-version: 1.14.3
lib-version: 1.14.3
build date: 2023-10-19T11:32+00:00
build revision: 1eb5a30a6ad0415550a9df632ac8832bf7e2bbba
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fplan9-extensions -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

```

**Comment by ErikEngerd** [comment]
Output of `cat /proc/cmdline`: 
`BOOT_IMAGE=/vmlinuz-6.1.0-16-amd64 root=/dev/mapper/node-root ro quiet systemd.unified_cgroup_hierarchy=0`

**Comment by ErikEngerd** [comment]
kubernetes version 1.27.3

**Comment by ErikEngerd** [comment]
I would appreciate any advice on how to troubleshoot this further. The problem is also not unique to the example container I am using. Other containers with pytorch/cuda that worked before also don't work anymore.

**Comment by ErikEngerd** [comment]
Stop the press! I have fixed the issue.

The main thing is to install the nvidia driver *not* using the nvidia instructions, but instead following the debian instructions at https://wiki.debian.org/NvidiaGraphicsDrivers#Debian_12_.22Bookworm.22

After this, nvidia-smi on the kubernetes node also shows the CUDA version as 12.0 instead of N/A as before. Now the test with `ctr run --rm --gpus 0 -t nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2 n` works, and also running a  gpu pod using kubernetes now works.  In both cases, I get the output

```
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

The main issue is most likely in the nvidia driver version since the debian installation installs a 525 version instead of a 545 version of the driver.
