### ISSUE TITLE
Allocate() need return mount path of libcuda

### ISSUE THREAD

**Issue by ScorpioCPH** [NVIDIA/k8s-device-plugin#5]
Hi, I'm trying to deploy `TensorFlow` (with GPU support) on kubernetes with this device plugin.
And some error occurred: 

```shell
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
```

After debug the source code I think this is because `Allocate` function don't return mount path of `libcuda.so`.

@flx42 PTAL, and I think i can send a PR to fix it later.

**Comment by 3XX0** [comment]
The device plugin only sets environment variables, all the GPU containerization process is done through nvidia-docker 2.0 (see README)

**Comment by ScorpioCPH** [comment]
@3XX0 Thanks, so i need to add `--runtime=nvidia` option to `docker run`?

**Comment by ScorpioCPH** [comment]
@3XX0 After change default runtime to `nvidia`, it works now. Thanks so much :-)
